version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: baroka:1.5
    container_name: baroka
    environment:
      - DB_URL=jdbc:mysql://db:3306/baroka
      - DB_USERNAME=demo
      - DB_PASSWORD=10041004
    depends_on:
      - db
    networks:
      - baroka_network
    ports:
      - "8080:8080"  # 필요에 따라 애플리케이션의 포트를 수정할 수 있습니다.

volumes:
  baroka_db_data:

networks:
  baroka_network:
    driver: bridge