version: '3.8'

services:
  app:
    image: zxz4641/baroka:1.6.1
    container_name: baroka
    environment:
      - BAROKA_PATH=~/.baroka
    volumes:
      - ./data:/data
    networks:
      - baroka_network
    ports:
      - "8080:8080"  # 필요에 따라 애플리케이션의 포트를 수정할 수 있습니다.

volumes:
  baroka_db_data:

networks:
  baroka_network:
    driver: bridge