version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: baroka:1.5
    container_name: baroka
    ports:
      - "8081:8080"
    volumes:
      - ./pem-keys:/pem-keys
    environment:
      DB_URL: jdbc:mysql://db:3306/baroka
      DB_USERNAME: demo
      DB_PASSWORD: 10041004
      BAROKA_PATH: ~/baroka
    depends_on:
      - db
    restart: always
    networks:
      - baroka_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 10041004
      MYSQL_DATABASE: baroka
      MYSQL_USER: demo
      MYSQL_PASSWORD: 10041004
    ports:
      - "3307:3306"
    volumes:
      - baroka_db_data:/var/lib/mysql
    networks:
      - baroka_network

volumes:
  baroka_db_data:

networks:
  baroka_network:
    driver: bridge
