version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: baroka:1.5
    container_name: baroka
    environment:
      - DB_URL=jdbc:mysql://db:3306/baroka
      - DB_USERNAME=demo
      - DB_PASSWORD=10041004
    depends_on:
      - db
    networks:
      - baroka_network
    ports:
      - "8080:8080"  # 필요에 따라 애플리케이션의 포트를 수정할 수 있습니다.

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 10041004
      MYSQL_DATABASE: baroka
      MYSQL_USER: demo
      MYSQL_PASSWORD: 10041004
    ports:
      - "3307:3306"
    volumes:
      - baroka_db_data:/var/lib/mysql
    networks:
      - baroka_network

volumes:
  baroka_db_data:

networks:
  baroka_network:
    driver: bridge